server:
  port: 8080
  servlet:
    context-path: /ejile

spring:
  datasource:
    url: jdbc:mysql://120.27.243.204:3306/ejile?&serverTimezone=Asia/Shanghai
    username: Tiger
    password: yang526163
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 120.27.243.204
    port: 6379
    password: yang123(*&

logging:
  level:
    com:
      qtztlink:
        ejile: debug
