server:
  port: 8080
  servlet:
    context-path: /ejile

spring:
  datasource:
    url: jdbc:mysql://120.27.243.204:3306/ejile?&serverTimezone=Asia/Shanghai
    username: Tiger
    password: yang526163
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 10000
      maximum-pool-size: 10
      minimum-idle: 3
      connection-test-query: SELECT 1
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: update
  redis:
    host: 120.27.243.204
    port: 6379
    password: ejile
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

logging:
  level:
    com:
      qtztlink:
        ejile: debug
